version: "3"

volumes:
  dependency-track-data:

services:
  dtrack-apiserver:
    image: dependencytrack/apiserver:snapshot
    ports:
      - "8081:8080"
    volumes:
      - "dependency-track-data:/data"
    restart: unless-stopped

  dtrack-frontend:
    image: dependencytrack/frontend:snapshot
    depends_on:
      - dtrack-apiserver
    environment:
      - "API_BASE_URL=http://localhost:8081"
      # - "BASE_PATH="
      # - "OIDC_ISSUER="
      # - "OIDC_CLIENT_ID="
      # - "OIDC_SCOPE="
      # - "OIDC_FLOW="
      # - "OIDC_LOGIN_BUTTON_TEXT="
    # volumes:
      # - "/host/path/to/config.json:/opt/owasp/dependency-track-frontend/static/config.json"
    ports:
      - "8080:8080"
    restart: unless-stopped

