export const GLOBAL_VULNERABILITY_AUDIT = 'GLOBAL_VULNERABILITY_AUDIT';
export const GLOBAL_POLICY_VIOLATION_AUDIT = 'GLOBAL_POLICY_VIOLATION_AUDIT';
export const WORKFLOW_ENGINE = 'WORKFLOW_ENGINE';
